apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka
    component: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-broker
    spec:
      containers:
      - name: kafka
        image: cloudtrackinc/kubernetes-kafka
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: kafka-zoo-svc:2181
          - name: KAFKA_CREATE_TOPICS
            value: demo-topic:16:1
        lifecycle:
          postStart:
            exec:
              Command: ["kafka-autoextend-partitions.sh","up"]
          preStop:
            exec:
              Command: ["kafka-autoextend-partitions.sh","down"]